name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DISPLAY: :99

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 11 ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Start Xvfb
      run: Xvfb :99 &
    - name: Run tests on Linux and Mac
      if: matrix.os != 'windows-latest'
      run: mvn -B test
    - name: Run recording test on Windows
      if: matrix.os == 'windows-latest'
      run: mvn -B test -Dtest=RecordingTest
    - name: Store recordings on Windows
      if: always() && matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: webm-files
        path: |
          C:\Users\runneradmin\Downloads\*.webm