# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DISPLAY: :99

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Start Xvfb
      run: Xvfb :99 &
    - name: Install Edge on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
        sudo apt install microsoft-edge-dev
    - name: Test with Maven
      run: mvn -B test
    - name: Store recordings
      uses: actions/upload-artifact@v3
      with:
        name: webm-files
        path: |
          **/*.webm