# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DISPLAY: :99
  GITHUB_TOKEN: ${{ secrets.WDM_GITHUBTOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 11 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Start Xvfb
      run: Xvfb :99 &
    - name: Install Edge on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
        sudo rm microsoft.gpg
        sudo apt update && sudo apt install microsoft-edge-stable
    - name: Test with Maven
      run: mvn -B test
    - name: Store recordings
      if: always() && matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: webm-files
        path: |
          C:\Users\runneradmin\Downloads\*.webm